### ISSUE TITLE
NGIX 502 ERROR://

### ISSUE THREAD

**Issue by prakasharyaman** [waldis-jr-dev/CapRover-flask#2]
Hey i just deployed your app exactly as it is on my site url flask.mysite.com but when i run this i am not able to see the output 
i have tried  flask.mysite.com/app but this also doesn't work . any help will be appreciated
<img width="791" alt="image" src="https://user-images.githubusercontent.com/63445447/159909747-ea182306-d749-4d73-a2f3-a9b721410639.png">

**Comment by grynov** [comment]
Hey
I will be more likely to help you if you provide more information on this issue.
Maybe server logs or smth like that.
